# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/alsa-mirza/flyrank-ml-internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

The lane that I have chosen is CTR Improvement by Search Position.
This problem is mainly based on prediction because the goal is to estimate the expected click-through rate (CTR) for web pages based on their SEO characteristics. The prediction helps in identifying pages that are performing below expectations and are needed to be improved.

The target variable in this case is CTR (Click Through Rate).
CTR represents the percentage of users who clicked on a search result after viewing it. This is the value that the machine learning model will learn to estimate.

A successful model should work effectively and should accurately estimate CTR for unseen pages. A lower prediction error means better performance. The predictions should help SEO specialists in identifying pages that deserve optimization.

In [9]:
!git clone https://github.com/alsa-mirza/flyrank-ml-internship.git

fatal: destination path 'flyrank-ml-internship' already exists and is not an empty directory.

In [10]:
import pandas as pd
df = pd.read_csv("flyrank-ml-internship/data/raw/content_refresh_anonymized.csv")
df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [11]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 30000
Columns: 44

In [12]:
df[['content_id', 'ctr', 'avg_position']].head(10)

             content_id   ctr  avg_position
0  content_304f48230142  0.76          10.6
1  content_a1fb4e703a9e  0.05          20.3
2  content_9aa793d4d895  0.09          36.5
3  content_331d6c4de07b  0.49           6.2
4  content_d99b7a2d90ca  0.13          44.0
5  content_d4084a4bc775  0.03           8.5
6  content_9a34b442b552  0.00           7.0
7  content_a63219c6e95a  0.06          21.2
8  content_5e6c160719bc  0.09          46.0
9  content_c27558df2b0c  0.16           4.9

The unit of analysis is one content page. Each row in the dataframe represents a single piece of content with its SEO and performance metrics. The dataframe includes information such as content ID, CTR, average search position, search volume, competition, content type, and other related features. This row-level data will allow the model to learn patterns that help identify which content pages have opportunities for CTR improvement.

In [13]:

df[['content_id', 'ctr', 'avg_position', 'search_volume', 'competition']].head(10)

             content_id   ctr  avg_position  search_volume  competition
0  content_304f48230142  0.76          10.6           10.0         0.67
1  content_a1fb4e703a9e  0.05          20.3           90.0         0.01
2  content_9aa793d4d895  0.09          36.5            0.0         0.00
3  content_331d6c4de07b  0.49           6.2           10.0         0.00
4  content_d99b7a2d90ca  0.13          44.0            0.0         0.00
5  content_d4084a4bc775  0.03           8.5          720.0         1.00
6  content_9a34b442b552  0.00           7.0            0.0         0.00
7  content_a63219c6e95a  0.06          21.2          590.0         0.44
8  content_5e6c160719bc  0.09          46.0            0.0         0.00
9  content_c27558df2b0c  0.16           4.9            0.0         0.00

In [14]:
print("One row represents one content page (article).")
print("Total rows:", len(df))

One row represents one content page (article).
Total rows: 30000

A fixed rule cannot accurately identify which pages should be optimized and which should not be optimized because CTR depends on many factors such as search position, search volume, competition, content quality, and user intent. The relationship between these factors is not simple and changes across different pages. A machine learning model can learn patterns from historical data and estimate which pages have unusually low CTR for their position. This helps prioritize optimization opportunities more accurately than using a single threshold or manual rule.

Before you submit, confirm each line honestly:

- [✅] Every section above is filled — markdown thinking AND the code that backs it
- [✅] The notebook runs top to bottom with no errors (Runtime → Run all)
- [✅] No client names, URLs, or private queries anywhere
- [✅] My claims use careful words: observed, measured, directional, decision-support
- [✅] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.